solved open network issue3374
nodemcu/nodemcu-firmware pull request #3392
Opened 2021-01-31 16:14 UTC by blobule

Fixes #3374.

- [x] This PR is for the `dev` branch rather than for the `release` branch.
- [x] This PR is compliant with the [other contributing guidelines](https://github.com/nodemcu/nodemcu-firmware/blob/dev/CONTRIBUTING.md) as well (if not, please describe why).
- [x] I have thoroughly tested my contribution.
- [x] The code changes are reflected in the documentation at `docs/*`.

I fixed the bug, making sure an open network (without password) is handled correctly.
I tested it and it works perfectly.

2021-01-31 16:31 UTC, blobule commented
I compiled nodemcu for the first time to fix this bug, and it was a great experience. Congratulation for such a nice compiling setup.
I've been using nodemcu for years, but this is a first for me.
I hope this PR is satisfactory.

Should we add in the docs of enduser_setup a complete example of an adequate boot process (init.lua)?
Something like this...
```
print("Wating 10 seconds. Use t:stop() to cancel the init process...")
t=tmr.create()
t:alarm(10000,tmr.ALARM_SINGLE,function ()
	if wifi.sta.getip() then
		print("Wifi activated",wifi.sta.getip())
		dofile("go.lua")
	else
		print("No Wifi. Starting portal...")
		enduser_setup.start(
		  "Nodemcu setup",
		  function()
			wifi.sta.autoconnect(1)
			print("Wifi activated",wifi.sta.getip())
			dofile("go.lua")
		  end,
		  function(err, str)
		    print("enduser_setup: Err #" .. err .. ": " .. str)
		    -- schedule reboot?
		  end
		)
	end
end)
```
It would be nice to have such an example chunk for init.lua

2021-02-01 19:47 UTC, HHHartmann requested changes
The rest looks good.

2021-02-01 19:47 UTC, HHHartmann commented on app/modules/enduser_setup.c
> +  if (pwd_str == NULL) { pwd_str="wifi_password="; }
There should be an  ENDUSER_SETUP_DEBUG note about this.
Maybe
``` C
ENDUSER_SETUP_DEBUG("Password string not found. Setting to empty");
```

2021-02-01 19:47 UTC, HHHartmann commented on app/modules/enduser_setup.c
>      ENDUSER_SETUP_DEBUG("Password or SSID string not found");
Please adapt the Message. "SSID string not found"

2021-02-01 20:11 UTC, HHHartmann commented
> I compiled nodemcu for the first time to fix this bug, and it was a great experience. Congratulation for such a nice compiling setup.

Wellcome to the club!


> Should we add in the docs of enduser_setup a complete example of an adequate boot process (init.lua)?
> Something like this...
> 
> ```
> print("Wating 10 seconds. Use t:stop() to cancel the init process...")
> t=tmr.create()
> t:alarm(10000,tmr.ALARM_SINGLE,function ()
> 	if wifi.sta.getip() then
> 		print("Wifi activated",wifi.sta.getip())
> 		dofile("go.lua")
> 	else
> 		print("No Wifi. Starting portal...")
> 		enduser_setup.start(
> 		  "Nodemcu setup",
> 		  function()
> 			wifi.sta.autoconnect(1)
> 			print("Wifi activated",wifi.sta.getip())
> 			dofile("go.lua")
> 		  end,
> 		  function(err, str)
> 		    print("enduser_setup: Err #" .. err .. ": " .. str)
> 		    -- schedule reboot?
> 		  end
> 		)
> 	end
> end)
> ```
> 
> It would be nice to have such an example chunk for init.lua

The lua_examples folder would be a nice place for that. Maybe write a comment about what go.lua is (I can guess, but just to be clear)
Also set t=nil at the end
Maybe have some emphasis on waiting for Wifi too.

I think a different PR would be good for that.

2021-02-02 15:01 UTC, marcelstoer approved these changes

2021-02-02 15:03 UTC, marcelstoer commented
> The lua_examples folder would be a nice place for that....
> I think a different PR would be good for that.

Yes, and then link to it from the docs.

2021-02-02 15:04 UTC, marcelstoer commented
Oh, it's already here: #3395

2021-03-12 11:57 UTC, marcelstoer commented
@blobule could you please Gregor's comments?

2021-12-28 05:33 UTC, HHHartmann approved these changes

2024-02-05 06:11 UTC, merged